name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up default FOLDER & AWS_S3_BUCKET
        run: |
          echo "AWS_S3_BUCKET=secrets.AWS_S3_BUCKET_CONTAINER" >> $GITHUB_ENV
          echo "FOLDER=container" >> $GITHUB_ENV

      # Recognise which code has changed [host(container) or guest(header)] and trigger the workflow accordingly
      - name: Recognise which code has changed and trigger the workflow accordingly
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            container:
              - 'container/**'
            header:
              - 'header/**'

      - name: Set up FOLDER & AWS_S3_BUCKET var for guest (container)
        if: steps.changes.outputs.container == 'true'
        run: |
          echo "AWS_S3_BUCKET=secrets.AWS_S3_BUCKET_CONTAINER" >> $GITHUB_ENV
          echo "FOLDER=container" >> $GITHUB_ENV
      - name: Set up FOLDER & AWS_S3_BUCKET var for guest (header)
        if: steps.changes.outputs.header == 'true'
        run: |
          echo "AWS_S3_BUCKET=secrets.AWS_S3_BUCKET_HEADER" >> $GITHUB_ENV
          echo "FOLDER=header" >> $GITHUB_ENV

      - name: Import Node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm packages
        run: |
          cd ${{ env.FOLDER }}
          npm i
      - name: Build
        run: |
          cd ${{ env.FOLDER }}
          npm run build

      - name: Debug-1
        run: echo env.AWS_S3_BUCKET

      - name: Debug-2
        run: echo ${{ env.AWS_S3_BUCKET }}
      # AWS S3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
          SOURCE_DIR: "${{ env.FOLDER }}/dist" # optional: defaults to entire repository
      - run: echo "üçè This job's status is ${{ job.status }}."
